// Code generated by MockGen. DO NOT EDIT.
// Source: test.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "core_service/internal/domain"
	test "core_service/internal/usecase/test"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTestService is a mock of TestService interface.
type MockTestService struct {
	ctrl     *gomock.Controller
	recorder *MockTestServiceMockRecorder
}

// MockTestServiceMockRecorder is the mock recorder for MockTestService.
type MockTestServiceMockRecorder struct {
	mock *MockTestService
}

// NewMockTestService creates a new mock instance.
func NewMockTestService(ctrl *gomock.Controller) *MockTestService {
	mock := &MockTestService{ctrl: ctrl}
	mock.recorder = &MockTestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestService) EXPECT() *MockTestServiceMockRecorder {
	return m.recorder
}

// GetForAdmin mocks base method.
func (m *MockTestService) GetForAdmin(ctx context.Context, planID uuid.UUID) (*domain.TestView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForAdmin", ctx, planID)
	ret0, _ := ret[0].(*domain.TestView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForAdmin indicates an expected call of GetForAdmin.
func (mr *MockTestServiceMockRecorder) GetForAdmin(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForAdmin", reflect.TypeOf((*MockTestService)(nil).GetForAdmin), ctx, planID)
}

// GetForEmployee mocks base method.
func (m *MockTestService) GetForEmployee(ctx context.Context, userID, planID uuid.UUID) (*domain.TestView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForEmployee", ctx, userID, planID)
	ret0, _ := ret[0].(*domain.TestView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForEmployee indicates an expected call of GetForEmployee.
func (mr *MockTestServiceMockRecorder) GetForEmployee(ctx, userID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForEmployee", reflect.TypeOf((*MockTestService)(nil).GetForEmployee), ctx, userID, planID)
}

// GetForManager mocks base method.
func (m *MockTestService) GetForManager(ctx context.Context, managerID, planID uuid.UUID) (*domain.TestView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForManager", ctx, managerID, planID)
	ret0, _ := ret[0].(*domain.TestView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForManager indicates an expected call of GetForManager.
func (mr *MockTestServiceMockRecorder) GetForManager(ctx, managerID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForManager", reflect.TypeOf((*MockTestService)(nil).GetForManager), ctx, managerID, planID)
}

// Submit mocks base method.
func (m *MockTestService) Submit(ctx context.Context, input test.SubmitTestInput) (*domain.TestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, input)
	ret0, _ := ret[0].(*domain.TestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockTestServiceMockRecorder) Submit(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockTestService)(nil).Submit), ctx, input)
}
