// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "core_service/internal/domain"
	admin "core_service/internal/usecase/admin"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// AdminGetPlan mocks base method.
func (m *MockAdminService) AdminGetPlan(ctx context.Context, planID uuid.UUID) (*domain.PlanWithTasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetPlan", ctx, planID)
	ret0, _ := ret[0].(*domain.PlanWithTasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetPlan indicates an expected call of AdminGetPlan.
func (mr *MockAdminServiceMockRecorder) AdminGetPlan(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetPlan", reflect.TypeOf((*MockAdminService)(nil).AdminGetPlan), ctx, planID)
}

// AssignManager mocks base method.
func (m *MockAdminService) AssignManager(ctx context.Context, input admin.AssignManagerInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignManager", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignManager indicates an expected call of AssignManager.
func (mr *MockAdminServiceMockRecorder) AssignManager(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignManager", reflect.TypeOf((*MockAdminService)(nil).AssignManager), ctx, input)
}

// GetEmployeeProfileForAdmin mocks base method.
func (m *MockAdminService) GetEmployeeProfileForAdmin(ctx context.Context, employeeID uuid.UUID) (*domain.EmployeeProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeProfileForAdmin", ctx, employeeID)
	ret0, _ := ret[0].(*domain.EmployeeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeProfileForAdmin indicates an expected call of GetEmployeeProfileForAdmin.
func (mr *MockAdminServiceMockRecorder) GetEmployeeProfileForAdmin(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeProfileForAdmin", reflect.TypeOf((*MockAdminService)(nil).GetEmployeeProfileForAdmin), ctx, employeeID)
}

// GetUser mocks base method.
func (m *MockAdminService) GetUser(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAdminServiceMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAdminService)(nil).GetUser), ctx, id)
}

// GetUserAvatar mocks base method.
func (m *MockAdminService) GetUserAvatar(ctx context.Context, userID uuid.UUID) (io.ReadCloser, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatar", ctx, userID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserAvatar indicates an expected call of GetUserAvatar.
func (mr *MockAdminServiceMockRecorder) GetUserAvatar(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatar", reflect.TypeOf((*MockAdminService)(nil).GetUserAvatar), ctx, userID)
}

// ListEmployeesByManager mocks base method.
func (m *MockAdminService) ListEmployeesByManager(ctx context.Context, managerID uuid.UUID) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeesByManager", ctx, managerID)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeesByManager indicates an expected call of ListEmployeesByManager.
func (mr *MockAdminServiceMockRecorder) ListEmployeesByManager(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeesByManager", reflect.TypeOf((*MockAdminService)(nil).ListEmployeesByManager), ctx, managerID)
}

// ListUsers mocks base method.
func (m *MockAdminService) ListUsers(ctx context.Context, input admin.ListUsersInput) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, input)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminServiceMockRecorder) ListUsers(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminService)(nil).ListUsers), ctx, input)
}

// RemoveManager mocks base method.
func (m *MockAdminService) RemoveManager(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveManager", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveManager indicates an expected call of RemoveManager.
func (mr *MockAdminServiceMockRecorder) RemoveManager(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveManager", reflect.TypeOf((*MockAdminService)(nil).RemoveManager), ctx, userID)
}

// UpdatePosition mocks base method.
func (m *MockAdminService) UpdatePosition(ctx context.Context, userID uuid.UUID, position string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, userID, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockAdminServiceMockRecorder) UpdatePosition(ctx, userID, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockAdminService)(nil).UpdatePosition), ctx, userID, position)
}

// UpdateRole mocks base method.
func (m *MockAdminService) UpdateRole(ctx context.Context, input admin.UpdateRoleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockAdminServiceMockRecorder) UpdateRole(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockAdminService)(nil).UpdateRole), ctx, input)
}
