// Code generated by MockGen. DO NOT EDIT.
// Source: skill.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "core_service/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSkillService is a mock of SkillService interface.
type MockSkillService struct {
	ctrl     *gomock.Controller
	recorder *MockSkillServiceMockRecorder
}

// MockSkillServiceMockRecorder is the mock recorder for MockSkillService.
type MockSkillServiceMockRecorder struct {
	mock *MockSkillService
}

// NewMockSkillService creates a new mock instance.
func NewMockSkillService(ctrl *gomock.Controller) *MockSkillService {
	mock := &MockSkillService{ctrl: ctrl}
	mock.recorder = &MockSkillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillService) EXPECT() *MockSkillServiceMockRecorder {
	return m.recorder
}

// ListByUserID mocks base method.
func (m *MockSkillService) ListByUserID(ctx context.Context, requesterID, userID uuid.UUID) ([]*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, requesterID, userID)
	ret0, _ := ret[0].([]*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockSkillServiceMockRecorder) ListByUserID(ctx, requesterID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockSkillService)(nil).ListByUserID), ctx, requesterID, userID)
}
