// Code generated by MockGen. DO NOT EDIT.
// Source: plan.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "core_service/internal/domain"
	plan "core_service/internal/usecase/plan"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPlanService is a mock of PlanService interface.
type MockPlanService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanServiceMockRecorder
}

// MockPlanServiceMockRecorder is the mock recorder for MockPlanService.
type MockPlanServiceMockRecorder struct {
	mock *MockPlanService
}

// NewMockPlanService creates a new mock instance.
func NewMockPlanService(ctrl *gomock.Controller) *MockPlanService {
	mock := &MockPlanService{ctrl: ctrl}
	mock.recorder = &MockPlanServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanService) EXPECT() *MockPlanServiceMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockPlanService) Archive(ctx context.Context, managerID, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, managerID, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockPlanServiceMockRecorder) Archive(ctx, managerID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockPlanService)(nil).Archive), ctx, managerID, planID)
}

// Create mocks base method.
func (m *MockPlanService) Create(ctx context.Context, input plan.CreatePlanInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPlanServiceMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlanService)(nil).Create), ctx, input)
}

// CreateAI mocks base method.
func (m *MockPlanService) CreateAI(ctx context.Context, input plan.CreateAIInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAI", ctx, input)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAI indicates an expected call of CreateAI.
func (mr *MockPlanServiceMockRecorder) CreateAI(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAI", reflect.TypeOf((*MockPlanService)(nil).CreateAI), ctx, input)
}

// Delete mocks base method.
func (m *MockPlanService) Delete(ctx context.Context, managerID, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, managerID, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlanServiceMockRecorder) Delete(ctx, managerID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlanService)(nil).Delete), ctx, managerID, planID)
}

// GetByID mocks base method.
func (m *MockPlanService) GetByID(ctx context.Context, managerID, id uuid.UUID) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, managerID, id)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlanServiceMockRecorder) GetByID(ctx, managerID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlanService)(nil).GetByID), ctx, managerID, id)
}

// GetByIDWithTasks mocks base method.
func (m *MockPlanService) GetByIDWithTasks(ctx context.Context, managerID, id uuid.UUID) (*domain.PlanWithTasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithTasks", ctx, managerID, id)
	ret0, _ := ret[0].(*domain.PlanWithTasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithTasks indicates an expected call of GetByIDWithTasks.
func (mr *MockPlanServiceMockRecorder) GetByIDWithTasks(ctx, managerID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithTasks", reflect.TypeOf((*MockPlanService)(nil).GetByIDWithTasks), ctx, managerID, id)
}

// GetEmployeePlan mocks base method.
func (m *MockPlanService) GetEmployeePlan(ctx context.Context, employeeID, planID uuid.UUID) (*domain.PlanWithTasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeePlan", ctx, employeeID, planID)
	ret0, _ := ret[0].(*domain.PlanWithTasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeePlan indicates an expected call of GetEmployeePlan.
func (mr *MockPlanServiceMockRecorder) GetEmployeePlan(ctx, employeeID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeePlan", reflect.TypeOf((*MockPlanService)(nil).GetEmployeePlan), ctx, employeeID, planID)
}

// ListByManager mocks base method.
func (m *MockPlanService) ListByManager(ctx context.Context, managerID uuid.UUID) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByManager", ctx, managerID)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByManager indicates an expected call of ListByManager.
func (mr *MockPlanServiceMockRecorder) ListByManager(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByManager", reflect.TypeOf((*MockPlanService)(nil).ListByManager), ctx, managerID)
}

// ListEmployeePlans mocks base method.
func (m *MockPlanService) ListEmployeePlans(ctx context.Context, employeeID uuid.UUID) ([]*domain.PlanWithTasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeePlans", ctx, employeeID)
	ret0, _ := ret[0].([]*domain.PlanWithTasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeePlans indicates an expected call of ListEmployeePlans.
func (mr *MockPlanServiceMockRecorder) ListEmployeePlans(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeePlans", reflect.TypeOf((*MockPlanService)(nil).ListEmployeePlans), ctx, employeeID)
}

// Update mocks base method.
func (m *MockPlanService) Update(ctx context.Context, input plan.UpdatePlanInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlanServiceMockRecorder) Update(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlanService)(nil).Update), ctx, input)
}
