// Code generated by MockGen. DO NOT EDIT.
// Source: ai.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	ai "core_service/internal/usecase/ai"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAIService is a mock of AIService interface.
type MockAIService struct {
	ctrl     *gomock.Controller
	recorder *MockAIServiceMockRecorder
}

// MockAIServiceMockRecorder is the mock recorder for MockAIService.
type MockAIServiceMockRecorder struct {
	mock *MockAIService
}

// NewMockAIService creates a new mock instance.
func NewMockAIService(ctrl *gomock.Controller) *MockAIService {
	mock := &MockAIService{ctrl: ctrl}
	mock.recorder = &MockAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIService) EXPECT() *MockAIServiceMockRecorder {
	return m.recorder
}

// ExtractSkills mocks base method.
func (m *MockAIService) ExtractSkills(ctx context.Context, input ai.ExtractSkillsInput) ([]ai.SkillCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSkills", ctx, input)
	ret0, _ := ret[0].([]ai.SkillCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractSkills indicates an expected call of ExtractSkills.
func (mr *MockAIServiceMockRecorder) ExtractSkills(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSkills", reflect.TypeOf((*MockAIService)(nil).ExtractSkills), ctx, input)
}

// GeneratePlan mocks base method.
func (m *MockAIService) GeneratePlan(ctx context.Context, input ai.GeneratePlanInput) (*ai.GeneratedPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePlan", ctx, input)
	ret0, _ := ret[0].(*ai.GeneratedPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePlan indicates an expected call of GeneratePlan.
func (mr *MockAIServiceMockRecorder) GeneratePlan(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePlan", reflect.TypeOf((*MockAIService)(nil).GeneratePlan), ctx, input)
}
