// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "core_service/internal/domain"
	model "core_service/internal/repository/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// DeleteRefreshToken mocks base method.
func (m *MockAuthRepository) DeleteRefreshToken(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) DeleteRefreshToken(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).DeleteRefreshToken), ctx, jti)
}

// GetRefreshToken mocks base method.
func (m *MockAuthRepository) GetRefreshToken(ctx context.Context, jti string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, jti)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) GetRefreshToken(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).GetRefreshToken), ctx, jti)
}

// SaveRefreshToken mocks base method.
func (m *MockAuthRepository) SaveRefreshToken(ctx context.Context, e domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) SaveRefreshToken(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).SaveRefreshToken), ctx, e)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AssignManager mocks base method.
func (m *MockUserRepository) AssignManager(ctx context.Context, userID, managerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignManager", ctx, userID, managerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignManager indicates an expected call of AssignManager.
func (mr *MockUserRepositoryMockRecorder) AssignManager(ctx, userID, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignManager", reflect.TypeOf((*MockUserRepository)(nil).AssignManager), ctx, userID, managerID)
}

// ClearManagerAssignments mocks base method.
func (m *MockUserRepository) ClearManagerAssignments(ctx context.Context, managerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearManagerAssignments", ctx, managerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearManagerAssignments indicates an expected call of ClearManagerAssignments.
func (mr *MockUserRepositoryMockRecorder) ClearManagerAssignments(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearManagerAssignments", reflect.TypeOf((*MockUserRepository)(nil).ClearManagerAssignments), ctx, managerID)
}

// CountAdmins mocks base method.
func (m *MockUserRepository) CountAdmins(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAdmins", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAdmins indicates an expected call of CountAdmins.
func (mr *MockUserRepositoryMockRecorder) CountAdmins(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAdmins", reflect.TypeOf((*MockUserRepository)(nil).CountAdmins), ctx)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, u *domain.User) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, u)
}

// ExistsAdmin mocks base method.
func (m *MockUserRepository) ExistsAdmin(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsAdmin", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsAdmin indicates an expected call of ExistsAdmin.
func (mr *MockUserRepositoryMockRecorder) ExistsAdmin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsAdmin", reflect.TypeOf((*MockUserRepository)(nil).ExistsAdmin), ctx)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetById mocks base method.
func (m *MockUserRepository) GetById(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserRepository)(nil).GetById), ctx, id)
}

// ListEmployeesByManager mocks base method.
func (m *MockUserRepository) ListEmployeesByManager(ctx context.Context, managerID uuid.UUID) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeesByManager", ctx, managerID)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeesByManager indicates an expected call of ListEmployeesByManager.
func (mr *MockUserRepositoryMockRecorder) ListEmployeesByManager(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeesByManager", reflect.TypeOf((*MockUserRepository)(nil).ListEmployeesByManager), ctx, managerID)
}

// ListUsers mocks base method.
func (m *MockUserRepository) ListUsers(ctx context.Context, params model.ListUsersParams) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, params)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserRepositoryMockRecorder) ListUsers(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserRepository)(nil).ListUsers), ctx, params)
}

// RemoveManager mocks base method.
func (m *MockUserRepository) RemoveManager(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveManager", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveManager indicates an expected call of RemoveManager.
func (mr *MockUserRepositoryMockRecorder) RemoveManager(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveManager", reflect.TypeOf((*MockUserRepository)(nil).RemoveManager), ctx, userID)
}

// UpdateAvatar mocks base method.
func (m *MockUserRepository) UpdateAvatar(ctx context.Context, userID uuid.UUID, avatarKey *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, avatarKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockUserRepositoryMockRecorder) UpdateAvatar(ctx, userID, avatarKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockUserRepository)(nil).UpdateAvatar), ctx, userID, avatarKey)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, hashPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, hashPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(ctx, userID, hashPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), ctx, userID, hashPassword)
}

// UpdatePosition mocks base method.
func (m *MockUserRepository) UpdatePosition(ctx context.Context, userID uuid.UUID, position string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, userID, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockUserRepositoryMockRecorder) UpdatePosition(ctx, userID, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockUserRepository)(nil).UpdatePosition), ctx, userID, position)
}

// UpdateProfile mocks base method.
func (m *MockUserRepository) UpdateProfile(ctx context.Context, userID uuid.UUID, update *domain.UpdateUserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateProfile(ctx, userID, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateProfile), ctx, userID, update)
}

// UpdateRole mocks base method.
func (m *MockUserRepository) UpdateRole(ctx context.Context, userID uuid.UUID, role domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockUserRepositoryMockRecorder) UpdateRole(ctx, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockUserRepository)(nil).UpdateRole), ctx, userID, role)
}

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockPlanRepository) Archive(ctx context.Context, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockPlanRepositoryMockRecorder) Archive(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockPlanRepository)(nil).Archive), ctx, planID)
}

// Create mocks base method.
func (m *MockPlanRepository) Create(ctx context.Context, plan *domain.Plan) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, plan)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPlanRepositoryMockRecorder) Create(ctx, plan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlanRepository)(nil).Create), ctx, plan)
}

// CreateWithTasks mocks base method.
func (m *MockPlanRepository) CreateWithTasks(ctx context.Context, planID uuid.UUID, tasks []*domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTasks", ctx, planID, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTasks indicates an expected call of CreateWithTasks.
func (mr *MockPlanRepositoryMockRecorder) CreateWithTasks(ctx, planID, tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTasks", reflect.TypeOf((*MockPlanRepository)(nil).CreateWithTasks), ctx, planID, tasks)
}

// Delete mocks base method.
func (m *MockPlanRepository) Delete(ctx context.Context, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlanRepositoryMockRecorder) Delete(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlanRepository)(nil).Delete), ctx, planID)
}

// GetByID mocks base method.
func (m *MockPlanRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlanRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlanRepository)(nil).GetByID), ctx, id)
}

// GetByIDWithTasks mocks base method.
func (m *MockPlanRepository) GetByIDWithTasks(ctx context.Context, id uuid.UUID) (*domain.PlanWithTasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithTasks", ctx, id)
	ret0, _ := ret[0].(*domain.PlanWithTasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithTasks indicates an expected call of GetByIDWithTasks.
func (mr *MockPlanRepositoryMockRecorder) GetByIDWithTasks(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithTasks", reflect.TypeOf((*MockPlanRepository)(nil).GetByIDWithTasks), ctx, id)
}

// GetEmployeePlan mocks base method.
func (m *MockPlanRepository) GetEmployeePlan(ctx context.Context, employeeID, planID uuid.UUID) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeePlan", ctx, employeeID, planID)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeePlan indicates an expected call of GetEmployeePlan.
func (mr *MockPlanRepositoryMockRecorder) GetEmployeePlan(ctx, employeeID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeePlan", reflect.TypeOf((*MockPlanRepository)(nil).GetEmployeePlan), ctx, employeeID, planID)
}

// ListAllByEmployeeID mocks base method.
func (m *MockPlanRepository) ListAllByEmployeeID(ctx context.Context, employeeID uuid.UUID) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByEmployeeID indicates an expected call of ListAllByEmployeeID.
func (mr *MockPlanRepositoryMockRecorder) ListAllByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByEmployeeID", reflect.TypeOf((*MockPlanRepository)(nil).ListAllByEmployeeID), ctx, employeeID)
}

// ListByEmployeeID mocks base method.
func (m *MockPlanRepository) ListByEmployeeID(ctx context.Context, employeeID uuid.UUID) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEmployeeID indicates an expected call of ListByEmployeeID.
func (mr *MockPlanRepositoryMockRecorder) ListByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEmployeeID", reflect.TypeOf((*MockPlanRepository)(nil).ListByEmployeeID), ctx, employeeID)
}

// ListByManager mocks base method.
func (m *MockPlanRepository) ListByManager(ctx context.Context, managerID uuid.UUID) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByManager", ctx, managerID)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByManager indicates an expected call of ListByManager.
func (mr *MockPlanRepositoryMockRecorder) ListByManager(ctx, managerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByManager", reflect.TypeOf((*MockPlanRepository)(nil).ListByManager), ctx, managerID)
}

// ManagerOwnsPlan mocks base method.
func (m *MockPlanRepository) ManagerOwnsPlan(ctx context.Context, managerID, planID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManagerOwnsPlan", ctx, managerID, planID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ManagerOwnsPlan indicates an expected call of ManagerOwnsPlan.
func (mr *MockPlanRepositoryMockRecorder) ManagerOwnsPlan(ctx, managerID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManagerOwnsPlan", reflect.TypeOf((*MockPlanRepository)(nil).ManagerOwnsPlan), ctx, managerID, planID)
}

// RecalculateProgress mocks base method.
func (m *MockPlanRepository) RecalculateProgress(ctx context.Context, planID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculateProgress", ctx, planID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecalculateProgress indicates an expected call of RecalculateProgress.
func (mr *MockPlanRepositoryMockRecorder) RecalculateProgress(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateProgress", reflect.TypeOf((*MockPlanRepository)(nil).RecalculateProgress), ctx, planID)
}

// Update mocks base method.
func (m *MockPlanRepository) Update(ctx context.Context, planID uuid.UUID, title string, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, planID, title, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlanRepositoryMockRecorder) Update(ctx, planID, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlanRepository)(nil).Update), ctx, planID, title, description)
}

// UpdateAIContent mocks base method.
func (m *MockPlanRepository) UpdateAIContent(ctx context.Context, planID uuid.UUID, title string, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAIContent", ctx, planID, title, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAIContent indicates an expected call of UpdateAIContent.
func (mr *MockPlanRepositoryMockRecorder) UpdateAIContent(ctx, planID, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAIContent", reflect.TypeOf((*MockPlanRepository)(nil).UpdateAIContent), ctx, planID, title, description)
}

// UpdateGenerationStatus mocks base method.
func (m *MockPlanRepository) UpdateGenerationStatus(ctx context.Context, planID uuid.UUID, status domain.GenerationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGenerationStatus", ctx, planID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGenerationStatus indicates an expected call of UpdateGenerationStatus.
func (mr *MockPlanRepositoryMockRecorder) UpdateGenerationStatus(ctx, planID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGenerationStatus", reflect.TypeOf((*MockPlanRepository)(nil).UpdateGenerationStatus), ctx, planID, status)
}

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CompleteTestingTask mocks base method.
func (m *MockTaskRepository) CompleteTestingTask(ctx context.Context, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTestingTask", ctx, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTestingTask indicates an expected call of CompleteTestingTask.
func (mr *MockTaskRepositoryMockRecorder) CompleteTestingTask(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTestingTask", reflect.TypeOf((*MockTaskRepository)(nil).CompleteTestingTask), ctx, planID)
}

// Create mocks base method.
func (m *MockTaskRepository) Create(ctx context.Context, task *domain.Task) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), ctx, task)
}

// Delete mocks base method.
func (m *MockTaskRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepository)(nil).GetByID), ctx, id)
}

// GetNextPosition mocks base method.
func (m *MockTaskRepository) GetNextPosition(ctx context.Context, planID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextPosition", ctx, planID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextPosition indicates an expected call of GetNextPosition.
func (mr *MockTaskRepositoryMockRecorder) GetNextPosition(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextPosition", reflect.TypeOf((*MockTaskRepository)(nil).GetNextPosition), ctx, planID)
}

// ListByPlanID mocks base method.
func (m *MockTaskRepository) ListByPlanID(ctx context.Context, planID uuid.UUID) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPlanID", ctx, planID)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPlanID indicates an expected call of ListByPlanID.
func (mr *MockTaskRepositoryMockRecorder) ListByPlanID(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPlanID", reflect.TypeOf((*MockTaskRepository)(nil).ListByPlanID), ctx, planID)
}

// Update mocks base method.
func (m *MockTaskRepository) Update(ctx context.Context, id uuid.UUID, title, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryMockRecorder) Update(ctx, id, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepository)(nil).Update), ctx, id, title, description)
}

// UpdateStatus mocks base method.
func (m *MockTaskRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockSkillRepository is a mock of SkillRepository interface.
type MockSkillRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRepositoryMockRecorder
}

// MockSkillRepositoryMockRecorder is the mock recorder for MockSkillRepository.
type MockSkillRepositoryMockRecorder struct {
	mock *MockSkillRepository
}

// NewMockSkillRepository creates a new mock instance.
func NewMockSkillRepository(ctrl *gomock.Controller) *MockSkillRepository {
	mock := &MockSkillRepository{ctrl: ctrl}
	mock.recorder = &MockSkillRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRepository) EXPECT() *MockSkillRepositoryMockRecorder {
	return m.recorder
}

// AttachToUser mocks base method.
func (m *MockSkillRepository) AttachToUser(ctx context.Context, userID, skillID, planID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachToUser", ctx, userID, skillID, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachToUser indicates an expected call of AttachToUser.
func (mr *MockSkillRepositoryMockRecorder) AttachToUser(ctx, userID, skillID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachToUser", reflect.TypeOf((*MockSkillRepository)(nil).AttachToUser), ctx, userID, skillID, planID)
}

// Create mocks base method.
func (m *MockSkillRepository) Create(ctx context.Context, skill *domain.Skill) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, skill)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSkillRepositoryMockRecorder) Create(ctx, skill interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSkillRepository)(nil).Create), ctx, skill)
}

// GetByName mocks base method.
func (m *MockSkillRepository) GetByName(ctx context.Context, name string) (*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSkillRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSkillRepository)(nil).GetByName), ctx, name)
}

// ListByUserID mocks base method.
func (m *MockSkillRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockSkillRepositoryMockRecorder) ListByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockSkillRepository)(nil).ListByUserID), ctx, userID)
}

// MockTestRepository is a mock of TestRepository interface.
type MockTestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestRepositoryMockRecorder
}

// MockTestRepositoryMockRecorder is the mock recorder for MockTestRepository.
type MockTestRepositoryMockRecorder struct {
	mock *MockTestRepository
}

// NewMockTestRepository creates a new mock instance.
func NewMockTestRepository(ctrl *gomock.Controller) *MockTestRepository {
	mock := &MockTestRepository{ctrl: ctrl}
	mock.recorder = &MockTestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRepository) EXPECT() *MockTestRepositoryMockRecorder {
	return m.recorder
}

// CreateAnswers mocks base method.
func (m *MockTestRepository) CreateAnswers(ctx context.Context, answers []*domain.TestAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswers", ctx, answers)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAnswers indicates an expected call of CreateAnswers.
func (mr *MockTestRepositoryMockRecorder) CreateAnswers(ctx, answers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswers", reflect.TypeOf((*MockTestRepository)(nil).CreateAnswers), ctx, answers)
}

// CreateAttempt mocks base method.
func (m *MockTestRepository) CreateAttempt(ctx context.Context, attempt *domain.TestAttempt) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempt", ctx, attempt)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttempt indicates an expected call of CreateAttempt.
func (mr *MockTestRepositoryMockRecorder) CreateAttempt(ctx, attempt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempt", reflect.TypeOf((*MockTestRepository)(nil).CreateAttempt), ctx, attempt)
}

// CreateWithQuestions mocks base method.
func (m *MockTestRepository) CreateWithQuestions(ctx context.Context, test *domain.Test, questions []*domain.Question) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithQuestions", ctx, test, questions)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithQuestions indicates an expected call of CreateWithQuestions.
func (mr *MockTestRepositoryMockRecorder) CreateWithQuestions(ctx, test, questions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithQuestions", reflect.TypeOf((*MockTestRepository)(nil).CreateWithQuestions), ctx, test, questions)
}

// GetAttempt mocks base method.
func (m *MockTestRepository) GetAttempt(ctx context.Context, testID, userID uuid.UUID) (*domain.TestAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttempt", ctx, testID, userID)
	ret0, _ := ret[0].(*domain.TestAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttempt indicates an expected call of GetAttempt.
func (mr *MockTestRepositoryMockRecorder) GetAttempt(ctx, testID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttempt", reflect.TypeOf((*MockTestRepository)(nil).GetAttempt), ctx, testID, userID)
}

// GetByPlanID mocks base method.
func (m *MockTestRepository) GetByPlanID(ctx context.Context, planID uuid.UUID) (*domain.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlanID", ctx, planID)
	ret0, _ := ret[0].(*domain.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPlanID indicates an expected call of GetByPlanID.
func (mr *MockTestRepositoryMockRecorder) GetByPlanID(ctx, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlanID", reflect.TypeOf((*MockTestRepository)(nil).GetByPlanID), ctx, planID)
}

// GetQuestions mocks base method.
func (m *MockTestRepository) GetQuestions(ctx context.Context, testID uuid.UUID) ([]*domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestions", ctx, testID)
	ret0, _ := ret[0].([]*domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestions indicates an expected call of GetQuestions.
func (mr *MockTestRepositoryMockRecorder) GetQuestions(ctx, testID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestions", reflect.TypeOf((*MockTestRepository)(nil).GetQuestions), ctx, testID)
}
